package br.com.carlos.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-08-11T20:22:10.411-03:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://ws.carlos.com.br/", name = "Calculadora")
@XmlSeeAlso({ObjectFactory.class})
public interface Calculadora {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "somar", targetNamespace = "http://ws.carlos.com.br/", className = "br.com.carlos.ws.Somar")
    @WebMethod
    @ResponseWrapper(localName = "somarResponse", targetNamespace = "http://ws.carlos.com.br/", className = "br.com.carlos.ws.SomarResponse")
    public int somar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
