
package br.com.carlos.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-08-11T20:22:10.371-03:00
 * Generated source version: 2.7.5
 * 
 */
public final class Calculadora_CalculadoraPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.carlos.com.br/", "CalculadoraService");

    private Calculadora_CalculadoraPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = new URL("http://localhost:8181/Calculadora?wsdl");
      
        CalculadoraService ss = new CalculadoraService(wsdlURL, SERVICE_NAME);
        Calculadora port = ss.getCalculadoraPort();  
        
        {
        System.out.println("Invoking somar...");
        int _somar_arg0 = 5;
        int _somar_arg1 = 3;
        int _somar__return = port.somar(_somar_arg0, _somar_arg1);
        System.out.println("somar.result=" + _somar__return);


        }

        System.exit(0);
    }

}
