package br.com.carlos.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2013-08-11T20:22:10.425-03:00
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "CalculadoraService", 
                  wsdlLocation = "file:/Users/prcarlosbarbero/Documents/ApacheCxfSpringHelloWorld-master/src/main/resources/calculadora.wsdl",
                  targetNamespace = "http://ws.carlos.com.br/") 
public class CalculadoraService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.carlos.com.br/", "CalculadoraService");
    public final static QName CalculadoraPort = new QName("http://ws.carlos.com.br/", "CalculadoraPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/prcarlosbarbero/Documents/ApacheCxfSpringHelloWorld-master/src/main/resources/calculadora.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculadoraService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/prcarlosbarbero/Documents/ApacheCxfSpringHelloWorld-master/src/main/resources/calculadora.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculadoraService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculadoraService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Calculadora
     */
    @WebEndpoint(name = "CalculadoraPort")
    public Calculadora getCalculadoraPort() {
        return super.getPort(CalculadoraPort, Calculadora.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Calculadora
     */
    @WebEndpoint(name = "CalculadoraPort")
    public Calculadora getCalculadoraPort(WebServiceFeature... features) {
        return super.getPort(CalculadoraPort, Calculadora.class, features);
    }

}
