package br.com.sulamerica;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-03-27T18:36:12.681-03:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "ConsultaElegibilidadeAutorizadorService", 
                  wsdlLocation = "http://saudeh.sulamerica.br/portalws/services/ConsultaElegibilidadeAutorizador?wsdl",
                  targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br") 
public class ConsultaElegibilidadeAutorizadorService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://autorizador.portalws.susis.sulamerica.com.br", "ConsultaElegibilidadeAutorizadorService");
    public final static QName ConsultaElegibilidadeAutorizador = new QName("http://autorizador.portalws.susis.sulamerica.com.br", "ConsultaElegibilidadeAutorizador");
    static {
        URL url = null;
        try {
            url = new URL("http://saudeh.sulamerica.br/portalws/services/ConsultaElegibilidadeAutorizador?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultaElegibilidadeAutorizadorService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://saudeh.sulamerica.br/portalws/services/ConsultaElegibilidadeAutorizador?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultaElegibilidadeAutorizadorService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultaElegibilidadeAutorizadorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaElegibilidadeAutorizadorService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaElegibilidadeAutorizadorService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaElegibilidadeAutorizadorService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConsultaElegibilidadeAutorizadorService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaElegibilidadeAutorizador
     */
    @WebEndpoint(name = "ConsultaElegibilidadeAutorizador")
    public ConsultaElegibilidadeAutorizador getConsultaElegibilidadeAutorizador() {
        return super.getPort(ConsultaElegibilidadeAutorizador, ConsultaElegibilidadeAutorizador.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaElegibilidadeAutorizador
     */
    @WebEndpoint(name = "ConsultaElegibilidadeAutorizador")
    public ConsultaElegibilidadeAutorizador getConsultaElegibilidadeAutorizador(WebServiceFeature... features) {
        return super.getPort(ConsultaElegibilidadeAutorizador, ConsultaElegibilidadeAutorizador.class, features);
    }

}
