package br.com.sulamerica;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-03-27T18:36:12.673-03:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br", name = "ConsultaElegibilidadeAutorizador")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsultaElegibilidadeAutorizador {

    @WebMethod
    @RequestWrapper(localName = "buscarListaTipoInternacao", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br", className = "br.com.sulamerica.BuscarListaTipoInternacao")
    @ResponseWrapper(localName = "buscarListaTipoInternacaoResponse", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br", className = "br.com.sulamerica.BuscarListaTipoInternacaoResponse")
    @WebResult(name = "buscarListaTipoInternacaoReturn", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
    public java.util.List<br.com.sulamerica.ListObjectTO> buscarListaTipoInternacao();

    @WebMethod
    @RequestWrapper(localName = "buscarListaCaraterSolicitacao", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br", className = "br.com.sulamerica.BuscarListaCaraterSolicitacao")
    @ResponseWrapper(localName = "buscarListaCaraterSolicitacaoResponse", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br", className = "br.com.sulamerica.BuscarListaCaraterSolicitacaoResponse")
    @WebResult(name = "buscarListaCaraterSolicitacaoReturn", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
    public java.util.List<br.com.sulamerica.ListObjectTO> buscarListaCaraterSolicitacao();

    @WebMethod
    @RequestWrapper(localName = "validarProcedimentos", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br", className = "br.com.sulamerica.ValidarProcedimentos")
    @ResponseWrapper(localName = "validarProcedimentosResponse", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br", className = "br.com.sulamerica.ValidarProcedimentosResponse")
    @WebResult(name = "validarProcedimentosReturn", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
    public br.com.sulamerica.RetornoServicoAutorizador validarProcedimentos(
        @WebParam(name = "codigoBeneficiario", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
        java.lang.String codigoBeneficiario,
        @WebParam(name = "codigoPrestador", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
        java.lang.String codigoPrestador,
        @WebParam(name = "tipoSolicitacao", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
        java.lang.String tipoSolicitacao,
        @WebParam(name = "caraterSolicitacao", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
        java.lang.String caraterSolicitacao,
        @WebParam(name = "dataPrevistaAtendimento", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
        java.lang.String dataPrevistaAtendimento,
        @WebParam(name = "tipoInternacao", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
        java.lang.String tipoInternacao,
        @WebParam(name = "regimeInternacao", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
        java.lang.String regimeInternacao,
        @WebParam(name = "qtdeDiarias", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
        java.math.BigInteger qtdeDiarias,
        @WebParam(name = "flgUsoVideo", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
        java.lang.String flgUsoVideo,
        @WebParam(name = "servicos", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
        java.util.List<br.com.sulamerica.ServicoAutorizador> servicos
    );

    @WebMethod
    @RequestWrapper(localName = "buscarServicoPorCodigo", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br", className = "br.com.sulamerica.BuscarServicoPorCodigo")
    @ResponseWrapper(localName = "buscarServicoPorCodigoResponse", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br", className = "br.com.sulamerica.BuscarServicoPorCodigoResponse")
    @WebResult(name = "buscarServicoPorCodigoReturn", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
    public br.com.sulamerica.ServicoAutorizador buscarServicoPorCodigo(
        @WebParam(name = "codigo", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
        java.lang.String codigo
    );

    @WebMethod
    @RequestWrapper(localName = "buscarListaTipoSolicitacaoElegibilidade", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br", className = "br.com.sulamerica.BuscarListaTipoSolicitacaoElegibilidade")
    @ResponseWrapper(localName = "buscarListaTipoSolicitacaoElegibilidadeResponse", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br", className = "br.com.sulamerica.BuscarListaTipoSolicitacaoElegibilidadeResponse")
    @WebResult(name = "buscarListaTipoSolicitacaoElegibilidadeReturn", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
    public java.util.List<br.com.sulamerica.ListObjectTO> buscarListaTipoSolicitacaoElegibilidade();

    @WebMethod
    @RequestWrapper(localName = "buscarServicoPorDescricao", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br", className = "br.com.sulamerica.BuscarServicoPorDescricao")
    @ResponseWrapper(localName = "buscarServicoPorDescricaoResponse", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br", className = "br.com.sulamerica.BuscarServicoPorDescricaoResponse")
    @WebResult(name = "buscarServicoPorDescricaoReturn", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
    public java.util.List<br.com.sulamerica.ServicoAutorizador> buscarServicoPorDescricao(
        @WebParam(name = "descricao", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
        java.lang.String descricao
    );

    @WebMethod
    @RequestWrapper(localName = "buscarListaRegimeInternacao", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br", className = "br.com.sulamerica.BuscarListaRegimeInternacao")
    @ResponseWrapper(localName = "buscarListaRegimeInternacaoResponse", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br", className = "br.com.sulamerica.BuscarListaRegimeInternacaoResponse")
    @WebResult(name = "buscarListaRegimeInternacaoReturn", targetNamespace = "http://autorizador.portalws.susis.sulamerica.com.br")
    public java.util.List<br.com.sulamerica.ListObjectTO> buscarListaRegimeInternacao();
}
