
package br.com.sulamerica;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2014-03-27T18:36:12.575-03:00
 * Generated source version: 2.5.1
 * 
 */
public final class ConsultaElegibilidadeAutorizador_ConsultaElegibilidadeAutorizador_Client {

    private static final QName SERVICE_NAME = new QName("http://autorizador.portalws.susis.sulamerica.com.br", "ConsultaElegibilidadeAutorizadorService");

    private ConsultaElegibilidadeAutorizador_ConsultaElegibilidadeAutorizador_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ConsultaElegibilidadeAutorizadorService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ConsultaElegibilidadeAutorizadorService ss = new ConsultaElegibilidadeAutorizadorService(wsdlURL, SERVICE_NAME);
        ConsultaElegibilidadeAutorizador port = ss.getConsultaElegibilidadeAutorizador();  
        
        {
        System.out.println("Invoking buscarListaTipoInternacao...");
        java.util.List<br.com.sulamerica.ListObjectTO> _buscarListaTipoInternacao__return = port.buscarListaTipoInternacao();
        System.out.println("buscarListaTipoInternacao.result=" + _buscarListaTipoInternacao__return);


        }
        {
        System.out.println("Invoking buscarListaCaraterSolicitacao...");
        java.util.List<br.com.sulamerica.ListObjectTO> _buscarListaCaraterSolicitacao__return = port.buscarListaCaraterSolicitacao();
        System.out.println("buscarListaCaraterSolicitacao.result=" + _buscarListaCaraterSolicitacao__return);


        }
        {
        System.out.println("Invoking validarProcedimentos...");
        java.lang.String _validarProcedimentos_codigoBeneficiario = "";
        java.lang.String _validarProcedimentos_codigoPrestador = "";
        java.lang.String _validarProcedimentos_tipoSolicitacao = "";
        java.lang.String _validarProcedimentos_caraterSolicitacao = "";
        java.lang.String _validarProcedimentos_dataPrevistaAtendimento = "";
        java.lang.String _validarProcedimentos_tipoInternacao = "";
        java.lang.String _validarProcedimentos_regimeInternacao = "";
        java.math.BigInteger _validarProcedimentos_qtdeDiarias = new java.math.BigInteger("0");
        java.lang.String _validarProcedimentos_flgUsoVideo = "";
        java.util.List<br.com.sulamerica.ServicoAutorizador> _validarProcedimentos_servicos = null;
        br.com.sulamerica.RetornoServicoAutorizador _validarProcedimentos__return = port.validarProcedimentos(_validarProcedimentos_codigoBeneficiario, _validarProcedimentos_codigoPrestador, _validarProcedimentos_tipoSolicitacao, _validarProcedimentos_caraterSolicitacao, _validarProcedimentos_dataPrevistaAtendimento, _validarProcedimentos_tipoInternacao, _validarProcedimentos_regimeInternacao, _validarProcedimentos_qtdeDiarias, _validarProcedimentos_flgUsoVideo, _validarProcedimentos_servicos);
        System.out.println("validarProcedimentos.result=" + _validarProcedimentos__return);


        }
        {
        System.out.println("Invoking buscarServicoPorCodigo...");
        java.lang.String _buscarServicoPorCodigo_codigo = "";
        br.com.sulamerica.ServicoAutorizador _buscarServicoPorCodigo__return = port.buscarServicoPorCodigo(_buscarServicoPorCodigo_codigo);
        System.out.println("buscarServicoPorCodigo.result=" + _buscarServicoPorCodigo__return);


        }
        {
        System.out.println("Invoking buscarListaTipoSolicitacaoElegibilidade...");
        java.util.List<br.com.sulamerica.ListObjectTO> _buscarListaTipoSolicitacaoElegibilidade__return = port.buscarListaTipoSolicitacaoElegibilidade();
        System.out.println("buscarListaTipoSolicitacaoElegibilidade.result=" + _buscarListaTipoSolicitacaoElegibilidade__return);


        }
        {
        System.out.println("Invoking buscarServicoPorDescricao...");
        java.lang.String _buscarServicoPorDescricao_descricao = "";
        java.util.List<br.com.sulamerica.ServicoAutorizador> _buscarServicoPorDescricao__return = port.buscarServicoPorDescricao(_buscarServicoPorDescricao_descricao);
        System.out.println("buscarServicoPorDescricao.result=" + _buscarServicoPorDescricao__return);


        }
        {
        System.out.println("Invoking buscarListaRegimeInternacao...");
        java.util.List<br.com.sulamerica.ListObjectTO> _buscarListaRegimeInternacao__return = port.buscarListaRegimeInternacao();
        System.out.println("buscarListaRegimeInternacao.result=" + _buscarListaRegimeInternacao__return);


        }

        System.exit(0);
    }

}
